// Code generated by 'yaegi extract github.com/kuchensheng/bintools/json/executor/util'. DO NOT EDIT.

package service

import (
	"github.com/kuchensheng/bintools/json/executor/util"
	"reflect"
)

func init() {
	Symbols["github.com/kuchensheng/bintools/json/executor/util/util"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"GetBodyParameterValue":    reflect.ValueOf(util.GetBodyParameterValue),
		"GetContextValue":          reflect.ValueOf(util.GetContextValue),
		"GetNotBodyParameterValue": reflect.ValueOf(util.GetNotBodyParameterValue),
		"GetResultValue":           reflect.ValueOf(util.GetResultValue),
		"ReadByJsonPath":           reflect.ValueOf(util.ReadByJsonPath),
		"SetResultValue":           reflect.ValueOf(util.SetResultValue),
	}
}
