// Code generated by 'yaegi extract github.com/kuchensheng/bintools/json/executor/js'. DO NOT EDIT.

package service

import (
	"github.com/kuchensheng/bintools/json/executor/js"
	"reflect"
)

func init() {
	Symbols["github.com/kuchensheng/bintools/json/executor/js/js"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ExecuteJavaScript": reflect.ValueOf(js.ExecuteJavaScript),
	}
}
