// Code generated by 'yaegi extract github.com/kuchensheng/bintools/json/executor/response'. DO NOT EDIT.

package service

import (
	"github.com/kuchensheng/bintools/json/executor/response"
	"reflect"
)

func init() {
	Symbols["github.com/kuchensheng/bintools/json/executor/response/response"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"BuildSuccessResponse": reflect.ValueOf(response.BuildSuccessResponse),
	}
}
