// Code generated by 'yaegi extract github.com/kuchensheng/bintools/json/executor/check'. DO NOT EDIT.

package service

import (
	"github.com/kuchensheng/bintools/json/executor/check"
	"reflect"
)

func init() {
	Symbols["github.com/kuchensheng/bintools/json/executor/check/check"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"CheckTenantId": reflect.ValueOf(check.CheckTenantId),
	}
}
