// Code generated by 'yaegi extract github.com/kuchensheng/bintools/json/executor/predicate'. DO NOT EDIT.

package service

import (
	"github.com/kuchensheng/bintools/json/executor/predicate"
	"reflect"
)

func init() {
	Symbols["github.com/kuchensheng/bintools/json/executor/predicate/predicate"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ExecPredicates": reflect.ValueOf(predicate.ExecPredicates),
	}
}
