server:
  port: 38240
  context: /api/app/orc/
  context-test : /api/app/test/orc/
  route:
    host: "http://10.30.30.81:38080"
    path: "/api/app/orc-server/**;/api/app/orc/**;/api/app/test/orc/**"
    serviceId: isc-json-engine
    url: http://isc-json-engine:38240
  go:
    path: D:\worksapace\go
  active: dev
login:
  # 是否启用权限拦截
  enable: true
  #权限服务地址（默认 http://isc-permission-service:32100）
  permissionUrl: http://10.30.30.78:38080
api-module: orc-server

