// Code generated by 'yaegi extract github.com/kuchensheng/bintools/json/executor/server'. DO NOT EDIT.

package lib

import (
	"github.com/kuchensheng/bintools/json/executor/server"
	"reflect"
)

func init() {
	Symbols["github.com/kuchensheng/bintools/json/executor/server/server"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ExecServer": reflect.ValueOf(server.ExecServer),
	}
}
