// Code generated by 'yaegi extract github.com/kuchensheng/bintools/json/executor/parameter'. DO NOT EDIT.

package lib

import (
	"github.com/kuchensheng/bintools/json/executor/parameter"
	"reflect"
)

func init() {
	Symbols["github.com/kuchensheng/bintools/json/executor/parameter/parameter"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"CheckParameter":  reflect.ValueOf(parameter.CheckParameter),
		"SetParameterMap": reflect.ValueOf(parameter.SetParameterMap),
	}
}
